const programRecords = [
  { value: 'BS Architecture', label: 'BS Architecture', department: 'School of Engineering and Architecture (SEA)' },
  { value: 'BS Aerospace Engineering (Academic Research)', label: 'BS Aerospace Engineering (Academic Research)', department: 'School of Engineering and Architecture (SEA)' },
  { value: 'BS Aerospace Engineering (Industry and Technopreneurship)', label: 'BS Aerospace Engineering (Industry and Technopreneurship)', department: 'School of Engineering and Architecture (SEA)' },
  { value: 'BS Civil Engineering (Construction Engineering and Management)', label: 'BS Civil Engineering (Construction Engineering and Management)', department: 'School of Engineering and Architecture (SEA)' },
  { value: 'BS Civil Engineering (Structural)', label: 'BS Civil Engineering (Structural)', department: 'School of Engineering and Architecture (SEA)' },
  { value: 'BS Civil Engineering (Transportation)', label: 'BS Civil Engineering (Transportation)', department: 'School of Engineering and Architecture (SEA)' },
  { value: 'BS Chemical Engineering', label: 'BS Chemical Engineering', department: 'School of Engineering and Architecture (SEA)' },
  { value: 'BS Computer Engineering', label: 'BS Computer Engineering', department: 'School of Engineering and Architecture (SEA)' },
  { value: 'BS Electrical Engineering', label: 'BS Electrical Engineering', department: 'School of Engineering and Architecture (SEA)' },
  { value: 'BS Electronics Engineering', label: 'BS Electronics Engineering', department: 'School of Engineering and Architecture (SEA)' },
  { value: 'BS Industrial Engineering', label: 'BS Industrial Engineering', department: 'School of Engineering and Architecture (SEA)' },
  { value: 'BS Mechanical Engineering', label: 'BS Mechanical Engineering', department: 'School of Engineering and Architecture (SEA)' },
  { value: 'BS Robotics Engineering', label: 'BS Robotics Engineering', department: 'School of Engineering and Architecture (SEA)' },
  { value: 'AB Anthropology', label: 'AB Anthropology', department: 'College of Arts and Sciences (CAS)' },
  { value: 'BS Biology Major in General Biology', label: 'BS Biology Major in General Biology', department: 'College of Arts and Sciences (CAS)' },
  { value: 'BS Biology Major in Medical Biology', label: 'BS Biology Major in Medical Biology', department: 'College of Arts and Sciences (CAS)' },
  { value: 'BS Chemistry', label: 'BS Chemistry', department: 'College of Arts and Sciences (CAS)' },
  { value: 'AB Communications', label: 'AB Communications', department: 'College of Arts and Sciences (CAS)' },
  { value: 'AB Development Studies', label: 'AB Development Studies', department: 'College of Arts and Sciences (CAS)' },
  { value: 'AB Economics', label: 'AB Economics', department: 'College of Arts and Sciences (CAS)' },
  { value: 'AB English Language', label: 'AB English Language', department: 'College of Arts and Sciences (CAS)' },
  { value: 'BS Environmental Science', label: 'BS Environmental Science', department: 'College of Computer Studies (CCS)' },
  { value: 'AB Interdisciplinary Studies Minor in Language and Literature', label: 'AB Interdisciplinary Studies Minor in Language and Literature', department: 'College of Arts and Sciences (CAS)' },
  { value: 'AB Interdisciplinary Studies Minor in Media and Business', label: 'AB Interdisciplinary Studies Minor in Media and Business', department: 'College of Arts and Sciences (CAS)' },
  { value: 'AB Interdisciplinary Studies Minor in Media and Philosophy', label: 'AB Interdisciplinary Studies Minor in Media and Philosophy', department: 'College of Arts and Sciences (CAS)' },
  { value: 'AB Interdisciplinary Studies Minor in Media and Technology', label: 'AB Interdisciplinary Studies Minor in Media and Technology', department: 'College of Arts and Sciences (CAS)' },
  { value: 'AB Interdisciplinary Studies Minor in Philosophy and Theology', label: 'AB Interdisciplinary Studies Minor in Philosophy and Theology', department: 'College of Arts and Sciences (CAS)' },
  { value: 'AB International Studies Major in American Studies', label: 'AB International Studies Major in American Studies', department: 'College of Arts and Sciences (CAS)' },
  { value: 'AB International Studies Major in Asian Studies', label: 'AB International Studies Major in Asian Studies', department: 'College of Arts and Sciences (CAS)' },
  { value: 'AB Islamic Studies Minor in Education', label: 'AB Islamic Studies Minor in Education', department: 'College of Arts and Sciences (CAS)' },
  { value: 'BS Mathematics', label: 'BS Mathematics', department: 'College of Arts and Sciences (CAS)' },
  { value: 'AB Philosophy', label: 'AB Philosophy', department: 'College of Arts and Sciences (CAS)' },
  { value: 'AB Political Science', label: 'AB Political Science', department: 'College of Arts and Sciences (CAS)' },
  { value: 'AB Psychology', label: 'AB Psychology', department: 'College of Arts and Sciences (CAS)' },
  { value: 'BS Psychology', label: 'BS Psychology', department: 'College of Arts and Sciences (CAS)' },
  { value: 'BS Social Work', label: 'BS Social Work', department: 'College of Arts and Sciences (CAS)' },
  { value: 'BS Sociology', label: 'BS Sociology', department: 'College of Arts and Sciences (CAS)' },
  { value: 'BS Computer Science', label: 'BS Computer Science', department: 'College of Computer Studies (CCS)' },
  { value: 'BS Data Science', label: 'BS Data Science', department: 'College of Computer Studies (CCS)' },
  { value: 'BS Information Systems', label: 'BS Information Systems', department: 'College of Computer Studies (CCS)' },
  { value: 'BS Information Technology', label: 'BS Information Technology', department: 'College of Computer Studies (CCS)' },
  { value: 'Bachelor of Elementary Education', label: 'Bachelor of Elementary Education', department: 'School of Education (SOE)' },
  { value: 'Bachelor of Secondary Education', label: 'Bachelor of Secondary Education', department: 'School of Education (SOE)' },
  { value: 'Bachelor of Secondary Education Major in English', label: 'Bachelor of Secondary Education Major in English', department: 'School of Education (SOE)' },
  { value: 'Bachelor of Secondary Education Major in Mathematics', label: 'Bachelor of Secondary Education Major in Mathematics', department: 'School of Education (SOE)' },
  { value: 'Bachelor of Secondary Education Major in Social Studies', label: 'Bachelor of Secondary Education Major in Social Studies', department: 'School of Education (SOE)' },
  { value: 'Bachelor of Secondary Education Major in Science', label: 'Bachelor of Secondary Education Major in Science', department: 'School of Education (SOE)' },
  { value: 'BS Accountancy', label: 'BS Accountancy', department: 'College of Business (COB)' },
  { value: 'BS Business Management', label: 'BS Business Management', department: 'College of Business (COB)' },
  { value: 'BS Entrepreneurship', label: 'BS Entrepreneurship', department: 'College of Business (COB)' },
  { value: 'BS Entrepreneurship Major in Agri-Business', label: 'BS Entrepreneurship Major in Agri-Business', department: 'College of Business (COB)' },
  { value: 'BS Finance', label: 'BS Finance', department: 'College of Business (COB)' },
  { value: 'BS Human Resource Development and Management', label: 'BS Human Resource Development and Management', department: 'College of Business (COB)' },
  { value: 'BS Management Accounting', label: 'BS Management Accounting', department: 'College of Business (COB)' },
  { value: 'BS Marketing', label: 'BS Marketing', department: 'College of Business (COB)' },
  { value: 'BS Public Management', label: 'BS Public Management', department: 'College of Business (COB)' },
  { value: 'BS Nursing', label: 'BS Nursing', department: 'School of Nursing (SON)' },
];

const categoryByProgram = {
  'BS Architecture': 'Engineering and Architecture', 'BS Aerospace Engineering (Academic Research)': 'Engineering and Architecture', 'BS Aerospace Engineering (Industry and Technopreneurship)': 'Engineering and Architecture', 'BS Civil Engineering (Construction Engineering and Management)': 'Engineering and Architecture', 'BS Civil Engineering (Structural)': 'Engineering and Architecture', 'BS Civil Engineering (Transportation)': 'Engineering and Architecture', 'BS Chemical Engineering': 'Engineering and Architecture', 'BS Computer Engineering': 'Engineering and Architecture', 'BS Electrical Engineering': 'Engineering and Architecture', 'BS Electronics Engineering': 'Engineering and Architecture', 'BS Industrial Engineering': 'Engineering and Architecture', 'BS Mechanical Engineering': 'Engineering and Architecture', 'BS Robotics Engineering': 'Engineering and Architecture',
  'AB Anthropology': 'Social Sciences', 'BS Biology Major in General Biology': 'Natural Sciences and Mathematics', 'BS Biology Major in Medical Biology': 'Natural Sciences and Mathematics', 'BS Chemistry': 'Natural Sciences and Mathematics', 'AB Communications': 'Humanities and Letters', 'AB Development Studies': 'Social Sciences', 'AB Economics': 'Social Sciences', 'AB English Language': 'Humanities and Letters', 'BS Environmental Science': 'Natural Sciences and Mathematics', 'AB Interdisciplinary Studies Minor in Language and Literature': 'Humanities and Letters', 'AB Interdisciplinary Studies Minor in Media and Business': 'Humanities and Letters  ', 'AB Interdisciplinary Studies Minor in Media and Philosophy': 'Humanities and Letters', 'AB Interdisciplinary Studies Minor in Media and Technology': 'Humanities and Letters', 'AB Interdisciplinary Studies Minor in Philosophy and Theology': 'Humanities and Letters', 'AB International Studies Major in American Studies': 'Social Sciences', 'AB International Studies Major in Asian Studies': 'Social Sciences', 'AB Islamic Studies Minor in Education': 'Social Sciences', 'BS Mathematics': 'Natural Sciences and Mathematics', 'AB Philosophy': 'Humanities and Letters', 'AB Political Science': 'Social Sciences', 'AB Psychology': 'Social Sciences', 'BS Psychology': 'Social Sciences', 'BS Social Work': 'Social Sciences', 'BS Sociology': 'Social Sciences',
  'BS Computer Science': 'Computer Studies', 'BS Data Science': 'Computer Studies', 'BS Information Systems': 'Computer Studies', 'BS Information Technology': 'Computer Studies', 'Bachelor of Elementary Education': 'Education', 'Bachelor of Secondary Education': 'Education', 'Bachelor of Secondary Education Major in English': 'Education', 'Bachelor of Secondary Education Major in Mathematics': 'Education', 'Bachelor of Secondary Education Major in Social Studies': 'Education', 'Bachelor of Secondary Education Major in Science': 'Education', 'BS Accountancy': 'Accountancy', 'BS Business Management': 'Business Administration', 'BS Entrepreneurship': 'Business Administration', 'BS Entrepreneurship Major in Agri-Business': 'Business Administration', 'BS Finance': 'Business Administration', 'BS Human Resource Development and Management': 'Business Administration', 'BS Management Accounting': 'Accountancy', 'BS Marketing': 'Business Administration', 'BS Public Management': 'Business Administration', 'BS Nursing': 'Nursing',
};

export const academicPrograms = programRecords.map((program) => ({ ...program, category: categoryByProgram[program.value] || 'Other programs' }));
export const academicProgramCategories = ['Accountancy', 'Business Administration', 'Computer Studies', 'Education', 'Engineering and Architecture', 'Humanities and Letters', 'Natural Sciences and Mathematics', 'Nursing', 'Social Sciences'];
export const getAcademicProgram = (value) => academicPrograms.find((program) => program.value === value) ?? academicPrograms[0];
