export const academicPrograms = [
  { value: 'BS Accountancy', label: 'BS Accountancy', department: 'College of Business (COB)' },
  { value: 'BS Accounting Information System', label: 'BS Accounting Information System', department: 'College of Business (COB)' },
  { value: 'BS Business Administration', label: 'BS Business Administration', department: 'College of Business (COB)' },
  { value: 'BS Management Accounting', label: 'BS Management Accounting', department: 'College of Business (COB)' },
  { value: 'BS Entrepreneurship', label: 'BS Entrepreneurship', department: 'College of Business (COB)' },
  { value: 'BS Computer Science', label: 'BS Computer Science', department: 'College of Computer Studies (CCS)' },
  { value: 'BS Information Technology', label: 'BS Information Technology', department: 'College of Computer Studies (CCS)' },
  { value: 'BS Information Systems', label: 'BS Information Systems', department: 'College of Computer Studies (CCS)' },
  { value: 'BS Data Science', label: 'BS Data Science', department: 'College of Computer Studies (CCS)' },
  { value: 'BS Architecture', label: 'BS Architecture', department: 'School of Engineering and Architecture (SEA)' },
  { value: 'BS Civil Engineering', label: 'BS Civil Engineering', department: 'School of Engineering and Architecture (SEA)' },
  { value: 'BS Computer Engineering', label: 'BS Computer Engineering', department: 'School of Engineering and Architecture (SEA)' },
  { value: 'BS Electrical Engineering', label: 'BS Electrical Engineering', department: 'School of Engineering and Architecture (SEA)' },
  { value: 'BS Electronics Engineering', label: 'BS Electronics Engineering', department: 'School of Engineering and Architecture (SEA)' },
  { value: 'BS Industrial Engineering', label: 'BS Industrial Engineering', department: 'School of Engineering and Architecture (SEA)' },
  { value: 'BS Mechanical Engineering', label: 'BS Mechanical Engineering', department: 'School of Engineering and Architecture (SEA)' },
  { value: 'BS Nursing', label: 'BS Nursing', department: 'School of Nursing (SON)' },
  { value: 'BS Biology', label: 'BS Biology', department: 'College of Arts and Sciences (CAS)' },
  { value: 'BS Psychology', label: 'BS Psychology', department: 'College of Arts and Sciences (CAS)' },
  { value: 'BA Communication', label: 'BA Communication', department: 'College of Arts and Sciences (CAS)' },
  { value: 'BA International Studies', label: 'BA International Studies', department: 'College of Arts and Sciences (CAS)' },
  { value: 'BS Mathematics', label: 'BS Mathematics', department: 'College of Arts and Sciences (CAS)' },
  { value: 'BA Philosophy', label: 'BA Philosophy', department: 'College of Arts and Sciences (CAS)' },
  { value: 'BS Criminology', label: 'BS Criminology', department: 'College of Arts and Sciences (CAS)' },
  { value: 'BS Public Administration', label: 'BS Public Administration', department: 'College of Arts and Sciences (CAS)' },
  { value: 'Bachelor of Elementary Education', label: 'Bachelor of Elementary Education', department: 'School of Education (SOE)' },
  { value: 'Bachelor of Secondary Education', label: 'Bachelor of Secondary Education', department: 'School of Education (SOE)' },
  { value: 'BS Nutrition and Dietetics', label: 'BS Nutrition and Dietetics', department: 'School of Health Sciences (SHS)' },
  { value: 'BS Hospitality Management', label: 'BS Hospitality Management', department: 'School of Hospitality and Tourism Management (SHTM)' },
  { value: 'BS Tourism Management', label: 'BS Tourism Management', department: 'School of Hospitality and Tourism Management (SHTM)' },
  { value: 'Other', label: 'Other program', department: 'Other / To be confirmed' },
];

export const getAcademicProgram = (value) => academicPrograms.find((program) => program.value === value) ?? academicPrograms[0];