const today = new Date();
const dateFromToday = (days) => {
  const date = new Date(today);
  date.setDate(date.getDate() + days);
  return date.toISOString().slice(0, 10);
};

export const degreePrograms = [
  'BS Computer Science',
  'BS Information Technology',
  'BS Business Administration',
  'BS Accountancy',
  'BS Psychology',
  'BS Civil Engineering',
  'BS Nursing',
  'BA Communication',
  'BS Biology',
  'BS Education',
];

const namedScholarships = [
  {
    title: 'Grant-in-Aid (GIA)',
    category: 'Internal Endowment',
    origin: 'AdDU Office of Student Affairs',
    coverageType: 'Full Tuition',
    coverage: 'Tuition and partial allowance support for economically challenged students.',
    minimumQpi: 2.5,
    maximumIncome: 300000,
    eligibleDegrees: ['ALL'],
    allowsMultipleGrants: false,
    departmentScope: 'All departments',
    deadline: dateFromToday(18),
    isActive: true,
    tags: ['urgent', 'endowment', 'need-based'],
  },
  {
    title: 'Jubilee Fund',
    category: 'Internal Endowment',
    origin: 'AdDU Donor Network',
    coverageType: 'Partial Tuition',
    coverage: 'Partial tuition relief and project support.',
    minimumQpi: 2.75,
    maximumIncome: 350000,
    eligibleDegrees: ['ALL'],
    allowsMultipleGrants: true,
    departmentScope: 'All departments',
    deadline: dateFromToday(31),
    isActive: true,
    tags: ['merit', 'donor-funded'],
  },
  {
    title: 'Jesuit Memorial Endowment',
    category: 'Internal Endowment',
    origin: 'AdDU Alumni and Benefactors',
    coverageType: 'Partial Tuition',
    coverage: 'Tuition support for academically strong applicants.',
    minimumQpi: 2.9,
    maximumIncome: 450000,
    eligibleDegrees: ['ALL'],
    allowsMultipleGrants: true,
    departmentScope: 'All departments',
    deadline: dateFromToday(46),
    isActive: true,
    tags: ['merit', 'legacy'],
  },
  {
    title: 'SM Foundation Scholarship',
    category: 'Corporate & External',
    origin: 'SM Foundation',
    coverageType: 'Full Tuition',
    coverage: 'Full tuition and academic allowance for qualified students.',
    minimumQpi: 2.75,
    maximumIncome: 250000,
    eligibleDegrees: ['BS Computer Science', 'BS Information Technology', 'BS Accountancy', 'BS Engineering'],
    allowsMultipleGrants: false,
    departmentScope: 'STEM and business programs',
    deadline: dateFromToday(22),
    isActive: true,
    tags: ['corporate', 'full tuition'],
  },
  {
    title: 'Aboitiz Future Leaders',
    category: 'Corporate & External',
    origin: 'Aboitiz Foundation',
    coverageType: 'Full Tuition',
    coverage: 'Tuition, allowance, and leadership development opportunities.',
    minimumQpi: 3.0,
    maximumIncome: 400000,
    eligibleDegrees: ['BS Computer Science', 'BS Information Technology', 'BS Business Administration', 'BS Engineering'],
    allowsMultipleGrants: false,
    departmentScope: 'High-performing students',
    deadline: dateFromToday(37),
    isActive: true,
    tags: ['leadership', 'corporate'],
  },
  {
    title: 'Davao Light (MICD)',
    category: 'Corporate & External',
    origin: 'Davao Light / MICD',
    coverageType: 'Partial Tuition',
    coverage: 'Scholarship assistance for selected program partners.',
    minimumQpi: 2.7,
    maximumIncome: 320000,
    eligibleDegrees: ['BS Engineering', 'BS Information Technology', 'BS Computer Science'],
    allowsMultipleGrants: false,
    departmentScope: 'Engineering and tech-related disciplines',
    deadline: dateFromToday(26),
    isActive: true,
    tags: ['corporate', 'stem'],
  },
  {
    title: 'CHED PESFA',
    category: 'State-Sponsored',
    origin: 'Commission on Higher Education',
    coverageType: 'Full Tuition',
    coverage: 'Government scholarship for priority degree programs.',
    minimumQpi: 2.5,
    maximumIncome: 300000,
    eligibleDegrees: ['ALL'],
    allowsMultipleGrants: false,
    departmentScope: 'Priority programs',
    deadline: dateFromToday(16),
    isActive: true,
    tags: ['government', 'priority'],
  },
  {
    title: 'DOST-SEI Merit',
    category: 'State-Sponsored',
    origin: 'Department of Science and Technology',
    coverageType: 'Full Tuition',
    coverage: 'STEM scholarship with stipend and book allowance.',
    minimumQpi: 2.75,
    maximumIncome: 400000,
    eligibleDegrees: ['BS Computer Science', 'BS Information Technology', 'BS Biology', 'BS Civil Engineering', 'BS Nursing'],
    allowsMultipleGrants: false,
    departmentScope: 'STEM and health programs',
    deadline: dateFromToday(29),
    isActive: true,
    tags: ['government', 'stem'],
  },
  {
    title: 'GSIS Subsidy',
    category: 'State-Sponsored',
    origin: 'Government Service Insurance System',
    coverageType: 'Partial Tuition',
    coverage: 'Financial assistance for dependent students.',
    minimumQpi: 2.25,
    maximumIncome: 450000,
    eligibleDegrees: ['ALL'],
    allowsMultipleGrants: true,
    departmentScope: 'All departments',
    deadline: dateFromToday(44),
    isActive: true,
    tags: ['government', 'subsidy'],
  },
  {
    title: 'Student Assistant (SA) Program',
    category: 'Specialized Service',
    origin: 'AdDU Student Employment Office',
    coverageType: 'Allowance',
    coverage: 'Campus work opportunities and monthly allowance.',
    minimumQpi: 2.0,
    maximumIncome: 350000,
    eligibleDegrees: ['ALL'],
    allowsMultipleGrants: true,
    departmentScope: 'All departments',
    deadline: dateFromToday(12),
    isActive: true,
    tags: ['service', 'work-study'],
  },
];

const categoryBlueprints = [
  { category: 'Internal Endowment', origin: 'AdDU Office of Student Affairs', coverageType: 'Partial Tuition', allowsMultipleGrants: true, maximumIncome: 420000, minimumQpi: 2.4 },
  { category: 'Corporate & External', origin: 'Partner Foundation', coverageType: 'Partial Tuition', allowsMultipleGrants: false, maximumIncome: 380000, minimumQpi: 2.7 },
  { category: 'State-Sponsored', origin: 'Government Agency', coverageType: 'Full Tuition', allowsMultipleGrants: false, maximumIncome: 300000, minimumQpi: 2.5 },
];

const genericScholarships = Array.from({ length: 54 - namedScholarships.length }, (_, index) => {
  const blueprint = categoryBlueprints[index % categoryBlueprints.length];
  const sequence = String(index + 1).padStart(2, '0');
  const categoryPrefix = blueprint.category === 'Internal Endowment' ? 'Endowment' : blueprint.category === 'Corporate & External' ? 'Partner Grant' : 'National Grant';
  const degreeScope = index % 4 === 0 ? ['ALL'] : [degreePrograms[index % degreePrograms.length], degreePrograms[(index + 3) % degreePrograms.length]];

  return {
    title: `${categoryPrefix} ${sequence}`,
    category: blueprint.category,
    origin: blueprint.origin,
    coverageType: blueprint.coverageType,
    coverage: `${blueprint.coverageType} support with deadline tracking and document-vault compatibility.`,
    minimumQpi: blueprint.minimumQpi + (index % 3) * 0.1,
    maximumIncome: blueprint.maximumIncome - (index % 5) * 10000,
    eligibleDegrees: degreeScope,
    allowsMultipleGrants: blueprint.allowsMultipleGrants || index % 5 === 0,
    departmentScope: index % 3 === 0 ? 'All departments' : degreeScope.join(', '),
    deadline: dateFromToday(10 + index),
    isActive: index % 13 !== 12,
    tags: [
      blueprint.category === 'State-Sponsored' ? 'government' : 'scholarship',
      index % 2 === 0 ? 'deadline-tracked' : 'faceted-search',
    ],
  };
});

export const scholarships = [...namedScholarships, ...genericScholarships].map((scholarship, index) => ({
  id: `sch-${String(index + 1).padStart(3, '0')}`,
  ...scholarship,
}));

const scholarshipByTitle = Object.fromEntries(scholarships.map((scholarship) => [scholarship.title, scholarship]));

export const demoUsers = {
  student: {
    id: 'user-student',
    role: 'student',
    fullName: 'Eriel John Espinosa',
    email: 'eriel@student.addu.edu.ph',
    phone: '+63 912 345 6789',
    department: 'BS Information Technology',
    degreeProgram: 'BS Information Technology',
    qpi: 2.86,
    householdIncome: 240000,
    hasActiveGovernmentGrant: false,
    bio: 'Undergraduate student looking for scholarship matches and deadline alerts.',
  },
  admin: {
    id: 'user-admin',
    role: 'osa_admin',
    fullName: 'OSA Administrator',
    email: 'osa@addu.edu.ph',
    phone: '+63 917 000 0000',
    department: 'Office of Student Affairs',
    degreeProgram: 'Administration',
    qpi: null,
    householdIncome: null,
    hasActiveGovernmentGrant: false,
    bio: 'Reviews applications, documents, announcements, and analytics.',
  },
  chair: {
    id: 'user-chair',
    role: 'department_chair',
    fullName: 'Department Chair',
    email: 'chair@addu.edu.ph',
    phone: '+63 918 000 0000',
    department: 'BS Computer Science',
    degreeProgram: 'BS Computer Science',
    qpi: null,
    householdIncome: null,
    hasActiveGovernmentGrant: false,
    bio: 'Evaluates GIA recommendations and endorses qualified students.',
  },
};

export const applications = [
  {
    id: 'app-001',
    studentId: 'user-student',
    scholarshipId: scholarshipByTitle['Grant-in-Aid (GIA)'].id,
    scholarshipTitle: 'Grant-in-Aid (GIA)',
    status: 'Under Review',
    documentStatus: 'Verified',
    submittedAt: dateFromToday(-3),
    updatedAt: dateFromToday(-1),
    attachedDocuments: ['doc-001', 'doc-002'],
    notes: 'Awaiting final OSA screening.',
  },
  {
    id: 'app-002',
    studentId: 'user-student',
    scholarshipId: scholarshipByTitle['DOST-SEI Merit'].id,
    scholarshipTitle: 'DOST-SEI Merit',
    status: 'Draft',
    documentStatus: 'Pending',
    submittedAt: null,
    updatedAt: dateFromToday(-2),
    attachedDocuments: ['doc-001'],
    notes: 'Profile saved for later submission.',
  },
];

export const documents = [
  {
    id: 'doc-001',
    ownerId: 'user-student',
    title: 'Academic Transcript',
    fileName: 'transcript.pdf',
    documentType: 'Transcript',
    verificationStatus: 'Verified',
    sharedWith: ['Grant-in-Aid (GIA)', 'DOST-SEI Merit'],
    uploadedAt: dateFromToday(-8),
  },
  {
    id: 'doc-002',
    ownerId: 'user-student',
    title: 'BIR-stamped ITR',
    fileName: 'itr.pdf',
    documentType: 'Income Proof',
    verificationStatus: 'Pending',
    sharedWith: ['Grant-in-Aid (GIA)'],
    uploadedAt: dateFromToday(-4),
  },
  {
    id: 'doc-003',
    ownerId: 'user-student',
    title: 'Certificate of Enrollment',
    fileName: 'coe.pdf',
    documentType: 'Enrollment',
    verificationStatus: 'Verified',
    sharedWith: ['DOST-SEI Merit'],
    uploadedAt: dateFromToday(-2),
  },
];

export const notifications = [
  {
    id: 'not-001',
    title: 'GIA deadline reminder',
    channel: 'SMS',
    body: 'Your Grant-in-Aid application is due in 3 days. Upload any missing documents now.',
    status: 'Unread',
    createdAt: dateFromToday(-1),
  },
  {
    id: 'not-002',
    title: 'Application status update',
    channel: 'Email',
    body: 'Your Grant-in-Aid application was moved to Under Review by OSA.',
    status: 'Unread',
    createdAt: dateFromToday(-1),
  },
  {
    id: 'not-003',
    title: 'Document verified',
    channel: 'In-app',
    body: 'Your academic transcript has been verified and can be reused across applications.',
    status: 'Read',
    createdAt: dateFromToday(-5),
  },
];

export const announcements = [
  {
    id: 'ann-001',
    title: 'OSA Scholarship Window Open',
    body: 'Students can now search, match, and submit scholarship applications from the centralized dashboard.',
    audience: 'Students',
    createdAt: dateFromToday(-2),
  },
  {
    id: 'ann-002',
    title: 'Document Review Queue Updated',
    body: 'Admin reviewers should clear pending proof-of-income documents before application finalization.',
    audience: 'OSA Admin',
    createdAt: dateFromToday(-1),
  },
];

export const departmentReviews = [
  {
    id: 'rev-001',
    studentName: 'Maria Clara Santos',
    department: 'BS Computer Science',
    qpi: 3.12,
    householdIncome: 210000,
    status: 'For Endorsement',
    recommendation: 'Qualified for GIA.',
  },
  {
    id: 'rev-002',
    studentName: 'John Paul Dizon',
    department: 'BS Information Technology',
    qpi: 2.84,
    householdIncome: 280000,
    status: 'Pending Documents',
    recommendation: 'Awaiting verified ITR before endorsement.',
  },
  {
    id: 'rev-003',
    studentName: 'Eleanor Cruz',
    department: 'BS Computer Science',
    qpi: 3.45,
    householdIncome: 180000,
    status: 'Endorsed',
    recommendation: 'Submitted to OSA for final approval.',
  },
];
